# Generated by Django 2.2.1 on 2019-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PLZO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('postcode', models.IntegerField()),
                ('additional_number', models.IntegerField()),
                ('community_name', models.CharField(max_length=255)),
                ('bfs_nr', models.IntegerField()),
                ('canton_abbrev', models.CharField(max_length=2)),
                ('wgs84_e', models.FloatField()),
                ('wgs84_n', models.FloatField()),
                ('lang', models.CharField(max_length=2)),
            ],
        ),
    ]
